<a href="https://colab.research.google.com/github/MuhammadHassan667410/Learning-Complete-Artificial-Intelligence/blob/main/Phase%201%20%3A%20Learning%20Python%20Fundamentals/LearnNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3])
# to specify dtype, do this
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [ ]:
b = np.array([[4.0,5.0,6.0],[7.0,8.0,9.0]])
print(b)

[[4. 5. 6.]
 [7. 8. 9.]]


In [ ]:
# Get dimension
a.ndim

1

In [ ]:
# get shape
b.shape
# (rows, colunms)

(2, 3)

In [ ]:
# get dataType
a.dtype

dtype('int16')

In [ ]:
# get size
a.itemsize

2

In [ ]:
# get total size
a.nbytes

6

Accessing/changing specific elements, rows, colunms etc

In [ ]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
# get a specific element [r, c]
c[1, 3]

np.int64(11)

In [ ]:
# get a specific row
c[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [ ]:
# get a specific colunm
c[:, 4]

array([ 5, 12])

In [ ]:
# get a little more fancy [row, startingindex:endingindex:stepsize] or [startingindex:endingindex:stepsize, colunm]
c[1, 3:7:1]

array([11, 12, 13, 14])

In [ ]:
# change element in the array
c[1,3] = 20
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 20 12 13 14]]


In [ ]:
# change a colunm in a array
c[:,3] = [22, 23]
print(c)

[[ 1  2  3 22  5  6  7]
 [ 8  9 10 23 12 13 14]]


3D example

In [ ]:
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# get specific element (work outside in)
d[0, 1, 1] #[select the 2D array within the 3D array, select the row within the chosen 2D array, select the colunm of the selected 2D array or element in the selected row]

np.int64(4)

In [ ]:
# get a specific row in a 2D ray within the 3D array
d[1, 0, :]
# get corresponding rows of both 2D rays in the 3D ray
d[:, 1, :]

array([[3, 4],
       [7, 8]])

In [ ]:
# get a specific colunm in a 2D ray within the 3D array
d[1, :, 0]
# get corresponding colunms of both 2D rays in the 3D ray
d[:, :, 1]

array([[2, 4],
       [6, 8]])

In [ ]:
# replace
# chose the specific element,row,colunm or corresponding rows,colunms of the 2D rays = what you want to replace
d[:, :, 1] = [[9, 11],[13,15]]
print(d)

[[[ 1  9]
  [ 3 11]]

 [[ 5 13]
  [ 7 15]]]


Initializing different types of arrays

In [ ]:
# All 0s matrix : np.zeros(shape of the matrix/array)
np.zeros((6,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
# 3D
np.zeros((2,3,6)) #(Num of 2D arrays, Num of rows in each 2D array, Num of colunms in each 2D array)

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [ ]:
# All 1s matrix
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [ ]:
# Any other matrix
np.full((3,2,6), 34) # (shape of matrix, the value of elements)

array([[[34, 34, 34, 34, 34, 34],
        [34, 34, 34, 34, 34, 34]],

       [[34, 34, 34, 34, 34, 34],
        [34, 34, 34, 34, 34, 34]],

       [[34, 34, 34, 34, 34, 34],
        [34, 34, 34, 34, 34, 34]]])

In [ ]:
# Initialize a matrix with the shape of any other matrix
np.full_like(d, 23) # (the matrix whose shape is to be copied, the value of elements)

array([[[23, 23],
        [23, 23]],

       [[23, 23],
        [23, 23]]])

In [ ]:
# Initialize a random decimal numbers matrix
np.random.rand(2,3)

array([[0.85086164, 0.46973757, 0.46236088],
       [0.29988247, 0.11933355, 0.76682475]])

In [ ]:
# copying shape of other matrix for a random matrix
np.random.random_sample(c.shape)

array([[0.5730888 , 0.91069354, 0.34954674, 0.99417635, 0.91326547,
        0.86968402, 0.03428853],
       [0.78669396, 0.27437233, 0.9488046 , 0.95474344, 0.89217317,
        0.30024776, 0.16708062]])

In [ ]:
# Random integer values
np.random.randint(5, 10, size=(4,3)) # (low, high, size=(rows,cols))

array([[8, 9, 5],
       [6, 8, 5],
       [9, 7, 7],
       [5, 5, 6]])

In [ ]:
# get identity matrix
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [ ]:
# repeat a array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 4, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
# practice
output = np.ones((5,5))

z = np.zeros((3,3))
z[1,1] = 9
output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# Be careful while copying arrays
#Donot do this
e = np.array([1,2,3])
f = e

# because if you want to change element in b,it will also change in a
f[0] = 33
print(e)
print(f)


[33  2  3]
[33  2  3]


In [ ]:
# Do this
g = ([1,2,3])
h = g.copy()
h[1] = 100
print(h)
print(g)

[1, 100, 3]
[1, 2, 3]


Mathematics

In [ ]:
i = np.array([1,2,3,4])
i

array([1, 2, 3, 4])

In [ ]:
i + 3

array([4, 5, 6, 7])

In [ ]:
i - 3

array([-2, -1,  0,  1])

In [ ]:
j = ([5,6,7,8])
j

[5, 6, 7, 8]

In [ ]:
i * j

array([ 5, 12, 21, 32])

In [ ]:
i + j

array([ 6,  8, 10, 12])

In [ ]:
# take sin,cos or tan
np.cos(i)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

Linear Algebra

In [ ]:
k = np.full((2,4), 4)
print(k)
l = np.full((4,2), 2)
print(l)
np.matmul(k,l)

[[4 4 4 4]
 [4 4 4 4]]
[[2 2]
 [2 2]
 [2 2]
 [2 2]]


array([[32, 32],
       [32, 32]])

In [ ]:
# Find determinant
m = np.random.randint(1,10, size=(2,2))
print(m)
np.linalg.det(m)

[[2 6]
 [5 4]]


np.float64(-22.000000000000004)

In [ ]:
n = np.invert(m)
print(n)
print(np.dot(m,n))

[[-3 -7]
 [-6 -5]]
[[-42 -44]
 [-39 -55]]


Statistics

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8,]])
np.min(a)
np.max(a)
np.mean(a)
np.diff(a)
np.median(a)

np.int64(8)

Reshaping arrays

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8,]])
after = before.reshape((4,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# Vertically stacking/combining vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [ ]:
#horizontal stacks
h1 = np.random.randint(2,100, size=(5,4))
h2 = np.random.randint(1,100, size=(5,2))
np.hstack([h1,h2])

array([[38, 82, 86, 71, 34, 50],
       [70, 77, 93, 77, 79, 71],
       [44, 94, 79, 72, 87, 92],
       [97, 50,  3, 28, 17, 39],
       [25,  9, 92, 57, 69, 33]])

Load Data from file

In [ ]:
with open('data.txt', 'w') as file:
  file.write('1,2,3,4,5,6,7,8\n')
  file.write('9,10,11,12,13,14,15,16\n')

In [ ]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)


[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [ ]:
filedata[filedata > 5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16], dtype=int32)

In [ ]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [ ]:
a[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [ ]:
a[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])